/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-12-29 04:38:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

import com.manage.domain.*;

import java.util.List;

public final class StudentCourse_jsp extends org.apache.jasper.runtime.HttpJspBase
        implements org.apache.jasper.runtime.JspSourceDependent,
        org.apache.jasper.runtime.JspSourceImports {

    private static final javax.servlet.jsp.JspFactory _jspxFactory =
            javax.servlet.jsp.JspFactory.getDefaultFactory();

    private static java.util.Map<java.lang.String, java.lang.Long> _jspx_dependants;

    static {
        _jspx_dependants = new java.util.HashMap<java.lang.String, java.lang.Long>(2);
        _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1577591658277L));
        _jspx_dependants.put("jar:file:/D:/project/Management/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Management/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    }

    private static final java.util.Set<java.lang.String> _jspx_imports_packages;

    private static final java.util.Set<java.lang.String> _jspx_imports_classes;

    static {
        _jspx_imports_packages = new java.util.HashSet<>();
        _jspx_imports_packages.add("javax.servlet");
        _jspx_imports_packages.add("javax.servlet.http");
        _jspx_imports_packages.add("com.manage.domain");
        _jspx_imports_packages.add("javax.servlet.jsp");
        _jspx_imports_classes = new java.util.HashSet<>();
        _jspx_imports_classes.add("java.util.List");
    }

    private volatile javax.el.ExpressionFactory _el_expressionfactory;
    private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

    public java.util.Map<java.lang.String, java.lang.Long> getDependants() {
        return _jspx_dependants;
    }

    public java.util.Set<java.lang.String> getPackageImports() {
        return _jspx_imports_packages;
    }

    public java.util.Set<java.lang.String> getClassImports() {
        return _jspx_imports_classes;
    }

    public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
        if (_el_expressionfactory == null) {
            synchronized (this) {
                if (_el_expressionfactory == null) {
                    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
                }
            }
        }
        return _el_expressionfactory;
    }

    public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
        if (_jsp_instancemanager == null) {
            synchronized (this) {
                if (_jsp_instancemanager == null) {
                    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
                }
            }
        }
        return _jsp_instancemanager;
    }

    public void _jspInit() {
    }

    public void _jspDestroy() {
    }

    public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
            throws java.io.IOException, javax.servlet.ServletException {

        final java.lang.String _jspx_method = request.getMethod();
        if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
            response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
            return;
        }

        final javax.servlet.jsp.PageContext pageContext;
        javax.servlet.http.HttpSession session = null;
        final javax.servlet.ServletContext application;
        final javax.servlet.ServletConfig config;
        javax.servlet.jsp.JspWriter out = null;
        final java.lang.Object page = this;
        javax.servlet.jsp.JspWriter _jspx_out = null;
        javax.servlet.jsp.PageContext _jspx_page_context = null;


        try {
            response.setContentType("text/html; charset=UTF-8");
            pageContext = _jspxFactory.getPageContext(this, request, response,
                    null, true, 8192, true);
            _jspx_page_context = pageContext;
            application = pageContext.getServletContext();
            config = pageContext.getServletConfig();
            session = pageContext.getSession();
            out = pageContext.getOut();
            _jspx_out = out;

            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("<!DOCTYPE html>\r\n");
            out.write("<html>\r\n");
            out.write("<head>\r\n");
            out.write("<meta charset=\"UTF-8\">\r\n");
            out.write("  <title>成绩打分</title>\r\n");
            out.write("    </head>\r\n");
            out.write("    <body>\r\n");
            out.write("   \t\t<script src=\"js/jquery-3.4.0.min.js\"></script>\r\n");
            out.write("   \t\t<script>\r\n");
            out.write("   \t\t$(function(){\r\n");
            out.write("            $(\"#submit\").click(function(){\r\n");
            out.write("                var grade = $(\"#grade\").val();\r\n");
            out.write("\t\t\t\t    var href_ = $(\"#submit\").attr(\"href\");\r\n");
            out.write("                $.trim(grade);\r\n");
            out.write("                var href_all = href_ + grade\r\n");
            out.write("\t\t\t\t    $(\"#submit\").attr(\"href\", href_all);  \r\n");
            out.write("            })\r\n");
            out.write("           })\r\n");
            out.write("   \t\t</script>\r\n");
            out.write("        <style>\r\n");
            out.write("             html{\r\n");
            out.write("                margin:0;\r\n");
            out.write("                width:100%;\r\n");
            out.write("                height:100%;\r\n");
            out.write("            }\r\n");
            out.write("            body{\r\n");
            out.write("                margin:0\r\n");
            out.write("            }\r\n");
            out.write("            a{\r\n");
            out.write("                text-decoration: none;\r\n");
            out.write("            }\r\n");
            out.write("            li {\r\n");
            out.write("                list-style-type: none;\r\n");
            out.write("            }\r\n");
            out.write("            \r\n");
            out.write("            .header{\r\n");
            out.write("                width: 100%; \r\n");
            out.write("                height:90px; \r\n");
            out.write("                border: 1px solid #cccccc;\r\n");
            out.write("                /* margin:auto 0; */\r\n");
            out.write("                background-color:#c8e4f0;\r\n");
            out.write("                text-align: center;\r\n");
            out.write("            }\r\n");
            out.write("            .header .headline{\r\n");
            out.write("                margin-right:62px;\r\n");
            out.write("                margin-left: 70px;\r\n");
            out.write("                margin-top:36px;\r\n");
            out.write("                font-size: 28px;\r\n");
            out.write("            }\r\n");
            out.write("            .main{\r\n");
            out.write("                width:100%;\r\n");
            out.write("                height:470px;\r\n");
            out.write("                background-color:whitesmoke; \r\n");
            out.write("                margin-top:2px;\r\n");
            out.write("                \r\n");
            out.write("            }\r\n");
            out.write("            .main-sector{\r\n");
            out.write("                width:888px;\r\n");
            out.write("                height:470px;\r\n");
            out.write("                margin:0 auto;\r\n");
            out.write("                background-color:#fff;\r\n");
            out.write("                text-align: center;\r\n");
            out.write("                border: 1px solid #c0c0c0;\r\n");
            out.write("                position:relative;\r\n");
            out.write("                \r\n");
            out.write("            }\r\n");
            out.write("            .option-ul{\r\n");
            out.write("                position: absolute;\r\n");
            out.write("                top:30px;\r\n");
            out.write("                left:98px;\r\n");
            out.write("                margin:0 auto;\r\n");
            out.write("                /* background-color:blueviolet; */\r\n");
            out.write("            }\r\n");
            out.write("            .option-ul li{\r\n");
            out.write("                height:52px;\r\n");
            out.write("                border-bottom: 1px solid #c0c0c0;\r\n");
            out.write("                text-align: center;\r\n");
            out.write("                line-height: 62px;\r\n");
            out.write("            }\r\n");
            out.write("        \r\n");
            out.write("       table th,td{ background:#FFF;\r\n");
            out.write("            border-width: 1px;\r\n");
            out.write("        \tpadding: 8px;\r\n");
            out.write("\t        border-style: solid;\r\n");
            out.write("\t        border-color: #a9c6c9;\r\n");
            out.write("\r\n");
            out.write("        } \r\n");
            out.write("        .table-d{\r\n");
            out.write("            /* margin:0 auto; */\r\n");
            out.write("             margin-left:105px;\r\n");
            out.write("            margin-top:28px; \r\n");
            out.write("        }\r\n");
            out.write("        .backword{\r\n");
            out.write("            /* float:right; */\r\n");
            out.write("            margin-right: 50px;\r\n");
            out.write("            position: absolute;\r\n");
            out.write("            top:68px;\r\n");
            out.write("            right:138px;\r\n");
            out.write("        }\r\n");
            out.write("        .grade{\r\n");
            out.write("            width: 100%;\r\n");
            out.write("            border:none; \r\n");
            out.write("            text-align:center;\r\n");
            out.write("        }\r\n");
            out.write("        /* .a-botton{\r\n");
            out.write("            position: absolute;\r\n");
            out.write("            bottom: 10px;\r\n");
            out.write("            right:188px;\r\n");
            out.write("        }\r\n");
            out.write("        button{\r\n");
            out.write("            width: 75px; height: 35px; font-size: 16px;\r\n");
            out.write("        } */\r\n");
            out.write("/* \r\n");
            out.write("css注释：设置table背景为红色，td背景为白色 */ \r\n");
            out.write("\r\n");
            out.write("        </style>\r\n");
            out.write("        \r\n");
            out.write("        ");

            List<StudentCourse> scs = (List<StudentCourse>) session.getAttribute("studentCourse");
            List<StudentInfo> sInfos = (List<StudentInfo>) session.getAttribute("students");
            if (scs != null && sInfos != null)
                for (StudentCourse sc : scs) {
                    for (StudentInfo sInfo : sInfos) {
                        if (sc.getSid().equals(sInfo.getsId()))
                            sc.setSname(sInfo.getName());
                    }
                }
            else {

                out.write("\r\n");
                out.write("       \t\t<h3>sc3 == 0 sInfo ==0</h3>\r\n");
                out.write("        \t");
            }
            out.write("\r\n");
            out.write("        \r\n");
            out.write("        <div class=\"header\">\r\n");
            out.write("            <h3 class=\"headline\">成绩打分</h3>\r\n");
            out.write("            <a class=\"backword\" href=\"TeacherIndex.jsp\">点击返回上一页</a>\r\n");
            out.write("        </div>\r\n");
            out.write("        <div class=\"main\">\r\n");
            out.write("            <div class=\"main-sector\">\r\n");
            out.write("                <!-- <ul class=\"option-ul\"> -->\r\n");
            out.write("                    \r\n");
            out.write("                <div class=\"table-d\">\r\n");
            out.write("                <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
            out.write("                    <tr>\r\n");
            out.write("                        <th>学号</th>\r\n");
            out.write("                        <th>姓名</th>\r\n");
            out.write("                        <th>课程代号</th>\r\n");
            out.write("                        <th>课程名</th>\r\n");
            out.write("                        <th>学分</th>\r\n");
            out.write("                        <th>成绩</th>\r\n");
            out.write("                        <th></th>\r\n");
            out.write("                    </tr>\r\n");
            out.write("                    ");

            if (scs != null) {
                for (StudentCourse sc : scs) {
                    if (sc.getGrade() == 0) {

                        out.write("\r\n");
                        out.write("                    <tr>\r\n");
                        out.write("                        <td>");
                        out.print(sc.getSid());
                        out.write("</td>\r\n");
                        out.write("                        <td>");
                        out.print(sc.getSname());
                        out.write("</td>\r\n");
                        out.write("                        <td>");
                        out.print(sc.getCid());
                        out.write("</td>\r\n");
                        out.write("                        <td>");
                        out.print(sc.getCname());
                        out.write("</td>\r\n");
                        out.write("                        <td>");
                        out.print(sc.getCredit());
                        out.write("</td>\r\n");
                        out.write("                        <td><input id=\"grade\" type=\"text\" name=\"grade\" class=\"grade\" value=\"\"></td>\r\n");
                        out.write("                        <td><a id=\"submit\" href=\"ModifyServlet?action=modifyGrade&cid=");
                        out.print(sc.getCid());
                        out.write("&sid=");
                        out.print(sc.getSid());
                        out.write("&grade=\">修改</a></td>\r\n");
                        out.write("                        <!-- <a class=\"a-botton\" href=\"#\"><button >提交</button></a> -->\r\n");
                        out.write("                    </tr>\r\n");
                        out.write("                    ");
                    }
                }
            }
            out.write("\r\n");
            out.write("                </table>\r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("\r\n");
            out.write("        </div>\r\n");
            out.write("    </body>\r\n");
            out.write("</html>");
        } catch (java.lang.Throwable t) {
            if (!(t instanceof javax.servlet.jsp.SkipPageException)) {
                out = _jspx_out;
                if (out != null && out.getBufferSize() != 0)
                    try {
                        if (response.isCommitted()) {
                            out.flush();
                        } else {
                            out.clearBuffer();
                        }
                    } catch (java.io.IOException e) {
                    }
                if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
                else throw new ServletException(t);
            }
        } finally {
            _jspxFactory.releasePageContext(_jspx_page_context);
        }
    }
}
