/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-12-29 05:51:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

import com.manage.domain.*;

import java.util.ArrayList;
import java.util.List;

public final class StudentIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
        implements org.apache.jasper.runtime.JspSourceDependent,
        org.apache.jasper.runtime.JspSourceImports {

    private static final javax.servlet.jsp.JspFactory _jspxFactory =
            javax.servlet.jsp.JspFactory.getDefaultFactory();

    private static java.util.Map<java.lang.String, java.lang.Long> _jspx_dependants;

    private static final java.util.Set<java.lang.String> _jspx_imports_packages;

    private static final java.util.Set<java.lang.String> _jspx_imports_classes;

    static {
        _jspx_imports_packages = new java.util.HashSet<>();
        _jspx_imports_packages.add("javax.servlet");
        _jspx_imports_packages.add("javax.servlet.http");
        _jspx_imports_packages.add("com.manage.domain");
        _jspx_imports_packages.add("javax.servlet.jsp");
        _jspx_imports_classes = new java.util.HashSet<>();
        _jspx_imports_classes.add("java.util.List");
        _jspx_imports_classes.add("java.util.ArrayList");
    }

    private volatile javax.el.ExpressionFactory _el_expressionfactory;
    private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

    public java.util.Map<java.lang.String, java.lang.Long> getDependants() {
        return _jspx_dependants;
    }

    public java.util.Set<java.lang.String> getPackageImports() {
        return _jspx_imports_packages;
    }

    public java.util.Set<java.lang.String> getClassImports() {
        return _jspx_imports_classes;
    }

    public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
        if (_el_expressionfactory == null) {
            synchronized (this) {
                if (_el_expressionfactory == null) {
                    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
                }
            }
        }
        return _el_expressionfactory;
    }

    public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
        if (_jsp_instancemanager == null) {
            synchronized (this) {
                if (_jsp_instancemanager == null) {
                    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
                }
            }
        }
        return _jsp_instancemanager;
    }

    public void _jspInit() {
    }

    public void _jspDestroy() {
    }

    public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
            throws java.io.IOException, javax.servlet.ServletException {

        final java.lang.String _jspx_method = request.getMethod();
        if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
            response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
            return;
        }

        final javax.servlet.jsp.PageContext pageContext;
        javax.servlet.http.HttpSession session = null;
        final javax.servlet.ServletContext application;
        final javax.servlet.ServletConfig config;
        javax.servlet.jsp.JspWriter out = null;
        final java.lang.Object page = this;
        javax.servlet.jsp.JspWriter _jspx_out = null;
        javax.servlet.jsp.PageContext _jspx_page_context = null;


        try {
            response.setContentType("text/html; charset=UTF-8");
            pageContext = _jspxFactory.getPageContext(this, request, response,
                    null, true, 8192, true);
            _jspx_page_context = pageContext;
            application = pageContext.getServletContext();
            config = pageContext.getServletConfig();
            session = pageContext.getSession();
            out = pageContext.getOut();
            _jspx_out = out;

            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("<!DOCTYPE html>\r\n");
            out.write("<html>\r\n");
            out.write("<head>\r\n");
            out.write("<meta charset=\"UTF-8\">\r\n");
            out.write("<title>学生成绩管理系统</title>\r\n");
            out.write("</head>\r\n");
            out.write("<body>\r\n");
            out.write("\t");

            //Student student = (Student)session.getAttribute("student");
            String sName = (String) session.getAttribute("sName");
            if (sName == null)
                response.sendRedirect("login.jsp");
            StudentInfo studentInfo = (StudentInfo) session.getAttribute("studentInfo");
            List<StudentCourse> scs = (List<StudentCourse>) session.getAttribute("StudentCourses");
            List<Course> chooseC = (List<Course>) session.getAttribute("chooseCourse");

            out.write("\r\n");
            out.write("\r\n");
            out.write("\t<script src=\"js/jquery-3.4.0.min.js\"></script>\r\n");
            out.write("\t<script src=\"js/Main.js\"></script>\r\n");
            out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\r\n");
            out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\">\r\n");
            out.write("\t<!-- <div class=\"wrapper\"> -->\r\n");
            out.write("\t<div class=\"header\">\r\n");
            out.write("\t\t<h2 class=\"headline\">学生信息综合管理系统</h2>\r\n");
            out.write("\t</div>\r\n");
            out.write("\t<div class=\"main\">\r\n");
            out.write("\t\t<div class=\"left-section\">\r\n");
            out.write("\r\n");
            out.write("\t\t\t<div class=\"left-inner-top\">\r\n");
            out.write("\t\t\t\t<img class=\"head-img\" src=\"images/52873718.png\" /> <span>");
            out.print(sName);
            out.write("<span>你好！\r\n");
            out.write("\t\t\t\t\t\t<a href=\"LoginServlet?action=logout\">退出</a>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\r\n");
            out.write("\t\t\t<div class=\"inner-option\">\r\n");
            out.write("\t\t\t\t<ul>\r\n");
            out.write("\t\t\t\t\t<li><input class=\"option\" type=\"radio\" name=\"nav2\" id=\"a1\">\r\n");
            out.write("\t\t\t\t\t\t<label class=\"op_label\" for=\"a1\">个人信息</label>\r\n");
            out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
            out.write("\t\t\t\t\t\t\t<h3>个人信息</h3>\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"info\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<table border=0 cellpadding=\"0\" cellspacing=\"0\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>学号</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>姓名</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>专业</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>年龄</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>性别</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>班级</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>职位</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>宿舍</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>电话</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>邮箱</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");

            if (studentInfo != null) {

                out.write("\r\n");
                out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
                out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                out.print(studentInfo.getsId());
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                out.print(studentInfo.getName());
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                out.print(studentInfo.getMajor());
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                out.print(studentInfo.getAge());
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                out.print(studentInfo.getSex());
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                out.print(studentInfo.getClass_());
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                out.print(studentInfo.getPosition());
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                out.print(studentInfo.getDormitory());
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                out.print(studentInfo.getPhoneNum());
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                out.print(studentInfo.getEmail());
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
                out.write("\t\t\t\t\t\t\t\t\t");

            }

            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t</table>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</div></li>\r\n");
            out.write("\t\t\t\t\t<li><input class=\"option\" type=\"radio\" name=\"nav2\" id=\"a3\">\r\n");
            out.write("\t\t\t\t\t\t<label class=\"op_label\" for=\"a3\">修改密码</label>\r\n");
            out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
            out.write("\t\t\t\t\t\t\t<h3>修改密码</h3>\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"modifyPW\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<form method=\"POST\" name=\"modifyPw\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\taction=\"ModifyServlet?action=modifyPw\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\tonsubmit=\"return modifyPw();\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<label>新密码</label> <input type=\"password\" id=\"pw1\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\tname=\"newPassword\"></br>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"pw2\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<label>再一次输入新密码</label> <input type=\"password\" id=\"pw2\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"rePassword\"></br>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"sid\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"");
            if (studentInfo != null) {
                out.print(studentInfo.getsId());
            }
            out.write("\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"submit\">\r\n");
            out.write("\t\t\t\t\t\t\t\t</form>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</div></li>\r\n");
            out.write("\t\t\t\t\t<li><input class=\"option\" type=\"radio\" name=\"nav2\" id=\"a4\">\r\n");
            out.write("\t\t\t\t\t\t<label class=\"op_label\" for=\"a4\">选课信息</label>\r\n");
            out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
            out.write("\t\t\t\t\t\t\t<h3>选课信息</h3>\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"table-info\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>课程代号</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>课程名称</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>学分</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th></th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t");
            if (studentInfo != null && chooseC != null && !chooseC.isEmpty()) {
                for (Course c : chooseC) {


                    out.write("\r\n");
                    out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
                    out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                    out.print(c.getCid());
                    out.write("</td>\r\n");
                    out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                    out.print(c.getCname());
                    out.write("</td>\r\n");
                    out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                    out.print(c.getCredit());
                    out.write("</td>\r\n");
                    out.write("\t\t\t\t\t\t\t\t\t\t<td><a href=\"ChooseCourseServlet?action=choose&cid=");
                    out.print(c.getCid());
                    out.write("&sid=");
                    out.print(studentInfo.getsId());
                    out.write("\">选课</a></td>\r\n");
                    out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
                    out.write("\t\t\t\t\t\t\t");
                }
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t</table>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t<li><input class=\"option\" type=\"radio\" name=\"nav2\" id=\"a5\">\r\n");
            out.write("\t\t\t\t\t\t<label class=\"op_label\" for=\"a5\">课程成绩</label>\r\n");
            out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
            out.write("\t\t\t\t\t\t\t<h3>课程成绩</h3>\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"table-info\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>课程代号</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>课程名称</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>学分</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>成绩</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            if (scs != null && !scs.isEmpty()) {
                for (StudentCourse sc : scs) {
                    if (sc.getGrade() != 0) {

                        out.write("\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                        out.print(sc.getCid());
                        out.write("</td>\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                        out.print(sc.getCname());
                        out.write("</td>\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                        out.print(sc.getCredit());
                        out.write(" </td>\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                        out.print(sc.getGrade());
                        out.write("</td>\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t");
                    }
                }
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t</table>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</div></li>\r\n");
            out.write("\t\t\t\t\t<li><input class=\"option\" type=\"radio\" name=\"nav2\" id=\"a6\">\r\n");
            out.write("\t\t\t\t\t\t<label class=\"op_label\" for=\"a6\">已选课程</label>\r\n");
            out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
            out.write("\t\t\t\t\t\t\t<h3>已选课程</h3>\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"table-info\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<table  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>课程号</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>课程名</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th>学分</th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<th></th>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            if (scs != null && !scs.isEmpty()) {
                for (StudentCourse sc : scs) {
                    if (sc.getGrade() == 0) {

                        out.write("\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                        out.print(sc.getCid());
                        out.write("</td>\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                        out.print(sc.getCname());
                        out.write("</td>\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t\t<td>");
                        out.print(sc.getCredit());
                        out.write("</td>\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t\t<td><a href=\"ChooseCourseServlet?action=giveup&cid=");
                        out.print(sc.getCid());
                        out.write("&sid=");
                        out.print(studentInfo.getsId());
                        out.write("\">弃选</a></td>\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
                        out.write("\t\t\t\t\t\t\t\t\t");
                    }
                }
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t</table>\r\n");
            out.write("\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t</div></li>\r\n");
            out.write("\t\t\t\t</ul>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\r\n");
            out.write("\t\t<div class=\"right-section\"></div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\t<!-- <div class=\"footer\"></div> -->\r\n");
            out.write("\t<!-- </div> -->\r\n");
            out.write("</body>\r\n");
            out.write("</html>");
        } catch (java.lang.Throwable t) {
            if (!(t instanceof javax.servlet.jsp.SkipPageException)) {
                out = _jspx_out;
                if (out != null && out.getBufferSize() != 0)
                    try {
                        if (response.isCommitted()) {
                            out.flush();
                        } else {
                            out.clearBuffer();
                        }
                    } catch (java.io.IOException e) {
                    }
                if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
                else throw new ServletException(t);
            }
        } finally {
            _jspxFactory.releasePageContext(_jspx_page_context);
        }
    }
}
