/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-12-28 13:17:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.manage.domain.*;

public final class TeacherIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.manage.domain");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>教师管理管理页面</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	Teacher teacher = (Teacher)session.getAttribute("teacher");
	if(teacher == null)
		response.sendRedirect("login.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\r\n");
      out.write("\t<style>\r\n");
      out.write(".header {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 90px;\r\n");
      out.write("\tborder: 1px solid #cccccc;\r\n");
      out.write("\t/* margin:auto 0; */\r\n");
      out.write("\tbackground-color: #c8e4f0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .headline {\r\n");
      out.write("\tmargin-right: 62px;\r\n");
      out.write("\tmargin-left: 70px;\r\n");
      out.write("\tmargin-top: 36px;\r\n");
      out.write("\tfont-size: 28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 470px;\r\n");
      out.write("\tbackground-color: whitesmoke;\r\n");
      out.write("\tmargin-top: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-sector {\r\n");
      out.write("\twidth: 370px;\r\n");
      out.write("\theight: 370px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tborder: 1px solid #c0c0c0;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".option-ul {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 88px;\r\n");
      out.write("\tleft: 98px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\t/* background-color:blueviolet; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".option-ul li {\r\n");
      out.write("\theight: 52px;\r\n");
      out.write("\tborder-bottom: 1px solid #c0c0c0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 62px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".option-ul li:hover {\r\n");
      out.write("\tbackground-color: khaki;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".teacherInfo {\r\n");
      out.write("\theight: 78px;\r\n");
      out.write("\tborder-bottom: 1px solid #c0c0cc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".teacherInfo div {\r\n");
      out.write("\tpadding-top: 48px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".teacherInfo a:hover {\r\n");
      out.write("\tbackground-color: khaki;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<h3 class=\"headline\">教师管理系统</h3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\t\t<div class=\"main-sector\">\r\n");
      out.write("\t\t\t<div class=\"teacherInfo\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t");
if(teacher!=null){
      out.print(teacher.getName() );
} 
      out.write("老师，你好！<a href=\"LoginServlet?action=logout\">退出</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"option-ul\">\r\n");
      out.write("\t\t\t\t<a href=\"StudentInfo.jsp\"><li>查看学生信息</li></a>\r\n");
      out.write("\t\t\t\t<!-- <li><a href=\"\">修改学生信息</a href=\"\"></li> -->\r\n");
      out.write("\t\t\t\t<a href=\"addCourse.jsp\"><li>添加课程</li></a>\r\n");
      out.write("\t\t\t\t<a href=\"Courses.jsp\"><li>查看课程</l href=\"\"i></a>\r\n");
      out.write("\t\t\t\t<a href=\"StudentCourse.jsp\"><li>成绩打分</l href=\"\"i></a>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
